### ISSUE TITLE
Using Offline Persistence

### ISSUE THREAD

**Issue by Yetispapa** [mono0926/flutter_firestore_ref#12]
Hi @mono0926,

first of all, thanks for the great framework! We currently investigating time to make the offline persistence running in our app. It seems that the offline feature is only working when not using transactions or await for requests (also mentioned [here](https://stackoverflow.com/questions/53549773/using-offline-persistence-in-firestore-in-a-flutter-app)) 

We can see that your flutter_firestore_ref code is completely build on those to keywords. Do you think it's possible to add a support for the offline persistence?

Thanks in advance

**Comment by mono0926** [comment]
firestore_ref is thin type-safe wrapper of cloud_firestore, so offline support is same as cloud_firestore.

> the offline feature is only working when not using transactions or await for requests (also mentioned here)

firestore_ref follows this.
